# This is a basic workflow to help you get started with Actions
name: Readme Update
# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Update README
        run: npm start
      - name: Commit README
        run: |
          git pull
          git add .
          git config --local user.email "ci980704@naver.com"
          git config --local user.name "choi-ik"
          git commit -m "Tistory 최근 발행글 업데이트" || echo "No changes to commit"
          git push || echo "Nothing to push"
